#ifndef C_EX_POKEMON_CLASSES_H
#define C_EX_POKEMON_CLASSES_H

#define CLASS_ARTIFICER  0
#define CLASS_BARBARIAN  1
#define CLASS_BARD       2
#define CLASS_CLERIC     3
#define CLASS_FIGHTER    4
#define CLASS_MONK       5
#define CLASS_RANGER     6
#define CLASS_WIZARD     7
#define CLASS_WARLOCK    8
#define CLASS_SORCERER   9
#define CLASS_PALADIN    10
#define CLASS_ROGUE      11
#define CLASS_DRUID      12

#define NUM_POKEMON_CLASSES 13

#define ROGUE_PRIORITY_DAMAGE_MULTIPLIER 1.5
#define MONK_MULTI_HIT_DAMAGE_MULTIPLIER 1.5
#define MONK_PUNCH_DAMAGE_MULTIPLIER 1.3
#define MONK_PHYSICAL_DAMAGE_MULTIPLIER 1.3
#define RANGER_NO_CONTACT_DAMAGE_MULTIPLIER 1.3
#define FIGHTER_SLICING_DAMAGE_MULTIPLIER 1.5
#define FIGHTER_PHYSICAL_DEFENCE_MULTIPLIER 0.5
#define FIGHTER_PHYSICAL_DAMAGE_MULTIPLIER 1.3
#define WIZARD_STAB_DAMAGE_MULTIPLIER 1.33
#define WIZARD_SUPER_EFFECTIVE_DAMAGE_MULTIPLIER 2.0
#define WIZARD_SUPER_EFFECTIVE_DEFENCE_MULTIPLIER 0.75
#define BARBARIAN_CONTACT_DAMAGE_MULTIPLIER 1.3
#define BARBARIAN_RECOIL_DAMAGE_MULTIPLIER 1.3
#define SORCERER_SPECIAL_DAMAGE_MULTIPLIER 1.2
#define SORCERER_PULSE_DAMAGE_MULTIPLIER 1.5
#define SORCERER_SPECIAL_DEFENCE_MULTIPLIER 0.5
#define BARD_SOUND_DAMAGE_MULTIPLIER 1.5
#define WARLOCK_ALL_DAMAGE_MULTIPLIER 1.1
#define ARTIFICER_GEM_DAMAGE_PERCENT 30
#define DRUID_TERRAIN_DAMAGE_MULTIPLIER 1.6
#define DRUID_TERRAIN_DEFENCE_MULTIPLIER 0.3
#define PALADIN_ALL_DEFENCE_MULTIPLIER 0.8
#define CLERIC_ABSORB_DAMAGE_MULTIPLIER 1.3

#define CLASS_LEVEL_UNO 30
#define CLASS_LEVEL_DUE 50

#endif //C_EX_POKEMON_CLASSES_H
