gText_ObtainedTheItem::
	.string "Obtained the {COLOR}{BLUE}{STR_VAR_2}{COLOR}{02}!$"

gText_TheBagIsFull::
	.string "The Bag is full…$"

gText_PutItemInPocket::
	.string "{COLOR}{BLUE}{PLAYER}{COLOR}{02} put away the {COLOR}{BLUE}{STR_VAR_2}{COLOR}{02}\n"
	.string "in the {COLOR}{BLUE}{STR_VAR_3} Pocket{COLOR}{02}.$"

gText_PlayerFoundOneItem::
	.string "{COLOR}{BLUE}{PLAYER}{COLOR}{02} found one {COLOR}{BLUE}{STR_VAR_2}{COLOR}{02}!$"

gText_TooBadBagIsFull::
	.string "Too bad!\n"
	.string "The Bag is full…$"

gText_PlayerPutItemInBag::
	.string "{COLOR}{BLUE}{PLAYER}{COLOR}{02} put away the {COLOR}{BLUE}{STR_VAR_2}{COLOR}{02}\n"
	.string "in the Bag.$"

gText_ObtainedTheDecor::
	.string "Obtained the {COLOR}{GREEN}{STR_VAR_2}{COLOR}{02}!$"

gText_NoRoomLeftForAnother::
	.string "Too bad! There's no room left for\n"
	.string "another {COLOR}{BLUE}{STR_VAR_2}{COLOR}{02}…$"

gText_TheDecorWasTransferredToThePC::
	.string "The {COLOR}{GREEN}{STR_VAR_2}{COLOR}{02} was transferred\n"
	.string "to the Chest.$"

gText_ObtainedTheItems::
	.string "Obtained {STR_VAR_1} {COLOR}{BLUE}{STR_VAR_2}{COLOR}{02}!$"

gText_PlayerFoundItems::
	.string "{COLOR}{BLUE}{PLAYER}{COLOR}{02} found {STR_VAR_1} {COLOR}{BLUE}{STR_VAR_2}{COLOR}{02}!$"
